### ISSUE TITLE
Docker not working; insufficient instructions to implement cli

### ISSUE THREAD

**Issue by mgkahn** [fhircat/FHIROntopOMOP#2]
Tool mentioned at recent OHDSI OMOP-FHIR kickoff. Trying to understand its use/purpose. Is there some description of what this tool does/intended use case?

Followed Docker instructions w/o success (see attached)
Unable to decipher CLI instructions -- insufficient details.
Maybe too early for external users?????

[FHIROntopOMOP_Docker_failure.txt](https://github.com/fhircat/FHIROntopOMOP/files/6950986/FHIROntopOMOP_Docker_failure.txt)

**Comment by gqjiang** [comment]
Did you set up the OMOP JDBC configuration to your own OMOP instance? 

at https://github.com/fhircat/FHIROntopOMOP/blob/main/input/fhir.properties

#Sat Dec 02 10:25:40 CST 2017
jdbc.url=jdbc\:postgresql\://localhost\:5433/mimic
jdbc.driver=org.postgresql.Driver
jdbc.user=postgres
jdbc.name=c9e990ba-d36c-4a99-8c3b-e3f01d12c4d7
jdbc.password=

**Comment by mgkahn** [comment]
Thanks for helping. Above didn't work. I did add the specific schema to the PG URI. I also replaced fhir.docker.properties with the same information I put into fhir.properties. I deleted the previous Docker image to create new images after my changes. Quietly returns the attached response and nothing @ localhost:8080. Since setting these properties is an expected step, need to include that information in the front README.md (and whatever steps we figure out to get me running!).  Still looking for any description what these tools are supposed to do. I'm seeking tools to help with OMOP --> FHIR translations.


![image](https://user-images.githubusercontent.com/3923918/128769272-23e94ebc-142f-4fec-a00d-22b42790c5bb.jpeg)




![image](https://user-images.githubusercontent.com/3923918/128769351-dda3c2b2-2785-4b8f-8ba8-2de7eb580a7e.jpeg)




![image](https://user-images.githubusercontent.com/3923918/128769661-62183d49-bd10-4719-819c-8ff10dcd2517.jpeg)




![image](https://user-images.githubusercontent.com/3923918/128769892-1f917e04-c338-4ec4-ad45-e8402d224259.jpeg)

**Comment by ghxiao** [comment]
Hi @mgkahn, please pull first as I just solved an issue of default schema.

The main problem is the connection to the database.
If I understood correctly, you are running the database and docker container on the same machine. In this case, there is a problem with `localhost`, since it refers to the docker container itself, but not the host machine with the database.

* If you are using Windows or Mac, you can use `host.docker.internal` as in https://github.com/ghxiao/FHIROntopOMOP/blob/main/input/fhir.docker.properties#L2

* If you are on Linux, check <https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach>
The command should be `sudo ip addr show docker0`.

The prototype is in an early stage but usable. I agree the documentation needs to be improved. I just updated a bit.

**Comment by ghxiao** [comment]
Hi @mgkahn 

The instruction has been further updated and simplified in the README file. It has also been tested on several machines.

Please let me know if you encounter any issues.

**Comment by mgkahn** [comment]
@ghxiao Thank you for continuing to make these tools accessible to others. I have not had the opportunity to move this work forward yet but will return to in in a month or so. I am going to close this issue and open a new one if I have challenges when I return to this agenda. Thanks again for all of your work/help.
